### ISSUE TITLE
Not Working :(

### ISSUE THREAD

**Issue by RyanCR03** [Virtuoel/Discarnate#1]
i get the channeling block and most of it works but when i use it in creative a vex spawns and dies quickly
and if i do it in survival it just plays a glass break sound. am i doing something wrong i need help

**Comment by Virtuoel** [comment]
The Channeler requires 3 things to function:
-  1 experience level (not required in creative)
- A Pumpkin on the player's head (configurable) (not required in creative)
- Task items in the Channeler block's inventory
   - Tasks will be executed left to right, top to bottom.
   - There is no delay between each task unless you add Wait Tasks in between others.
      - Tasks that perform actions over time have no inherent delay. e.g. If you place a stack 60 movement tasks (which is equivalent to holding the move forward key for 3 seconds), you'll want a stack of at least 60 wait tasks after them if you want the previous task to run on its own for the full 3 seconds, otherwise the movement task will begin moving you forward but will then terminate once the Channeler runs out of any remaining Wait Tasks and reaches end of the Task list.
      - This allows you to use, for example, a stack of 40 move forward tasks followed by 20 jump tasks, 20 delay tasks, 20 sneak tasks, and then 20 more delay tasks, which will result in 1 second of moving forward while jumping followed by one second of moving forward while sneaking.
